language: python
python:
- 3.6
cache: pip
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
#- make publish
- pelican content -s publishconf.py -D
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: output
  target_branch: gh-pages
  on:
    branch: master
